# ~/.config/starship.toml

# Move the directory to the second line
format = "$directory$character"

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# blank line at the start of the prompt
add_newline = true

[character]
success_symbol = "[❯](bold green) "
error_symbol = "[✖](bold red) "

[directory]
truncation_length = 1

